### ISSUE TITLE
Certificates signed by https://sectigo.com/ fail

### ISSUE THREAD

**Issue by jankoprowski** [certifi/python-certifi#106]
Hi,

  I'm using latest version 2019.9.11 of your library.
  For some reason connecting via requests library with web page certificate signed by https://sectigo.com/ cause following error:

```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852).
```

  Downloading certificate chain from web page and adding it into REQUESTS_CA_BUNDLE helps.

Regards,

Jan

**Comment by arthurlogilab** [comment]
We're affected by this too for access to https://archives.marne.fr/

**Comment by JosephHobbs** [comment]
As of the 2019.11.28 release this signer is included...  This issue can be closed out...

**Comment by jon-torodash** [comment]
Are you sure? I still get the error even with 2019.11.18, and the only commit since the prior release, 21abb9b9bbf4c0cfecf652fadafee3eb9615d553 (according to my diff), does not show Sectigo.  Am I missing something?

**Comment by JosephHobbs** [comment]
The certificate starting at line 3030 of cacerts.pem has the same issuer and SHA1 fingerprint as the cert on https://archives.marne.fr/.  This was the basis for my assumption that this signer is present.

**Comment by jon-torodash** [comment]
Thanks for the quick response. I'm not sure from where you got that data. The website you linked to above doesn't show me anything helpful, but may I ask that you take a look at https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA01N000000rfBO ? When I add the intermediate at `USERTrust RSA Certification Authority [ Root Certificate Cross Signed ]` to cacerts.pem, certifi works perfectly with the domain on which I have one of their purchased certs.
