### ISSUE TITLE
add a bootstrapping utility that makes the stdlib use certifi

### ISSUE THREAD

**Issue by glyph** [certifi/python-certifi#108]
There are a plethora of situations where you can end up with a Python whose stdlib doesn't point `SSL_CTX_set_default_verify_paths` at the right location for one reason or another.  (Arguably, this is the reason `certifi` exists.)

[The relevant PEP](https://www.python.org/dev/peps/pep-0476/) tells you to do this:

```python
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context
```

"though highly discouraged".

It's pretty obscure to figure out that you need to know that the underlying function is actually documented here: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_load_verify_locations.html and not in the stdlib.

`certifi` should come with a function that does *something* like this:

```python
import ssl
import certifi

def _create_certifi_context():
    return ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=certifi.where())
ssl._create_default_https_context = _create_certifi_context
```

and then document it clearly so that anyone wanting a functioning stdlib TLS client layer will get it by default.

**Comment by alex** [comment]
IMO this is beyond the scope of certifi, which should be to do literally nothing but distribute a PEM file.

**Comment by glyph** [comment]
> IMO this is beyond the scope of certifi, which should be to do literally nothing but distribute a PEM file.

Perhaps it should be a separate package that installs a `.pth` file that does this?  I'm not dead set on including this in `certifi` but it does feel like a 1-line glue function wouldn't be so far out of scope.

I've updated the description to do this in a way that actually works - to my point about how subtle this is, setting the env var works in normal dynamically linked builds of python, but embedded builds (where this is more of an issue) might have accidentally initialized OpenSSL too early.

**Comment by alex** [comment]
Going to close this on the reasoning I suggested in my previous message.
