### ISSUE TITLE
Docs page has invalid SSL certificate

### ISSUE THREAD

**Issue by foxx** [certifi/python-certifi#113]
https://certifi.kennethreitz.org/en/latest/

**Comment by alex** [comment]
https://certifi.io/en/latest/ is teh correct page. Is somethign linking to the page on kennethreitz.org?

**Comment by divbzero** [comment]
Related to #118?

**Comment by divbzero** [comment]
To answer my own question: #118 is a separate issue and probably unrelated.

@foxx probably tried navigating to https://certifiio.readthedocs.io/ which redirects to https://certifi.kennethreitz.org/en/latest/ as follows:

```http
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: certifiio.readthedocs.io
User-Agent: HTTPie/2.0.0
```
```http
HTTP/1.1 302 Found
Content-Language: en
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Wed, 11 Mar 2020 09:11:33 GMT
Location: https://certifi.kennethreitz.org/en/latest/
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Language, Cookie
X-Content-Type-Options: nosniff
X-Deity: web03
X-Frame-Options: DENY
X-RTD-System-Redirect: True
X-Served: Django-Proxito
X-XSS-Protection: 1; mode=block
```

Oddly, navigating directly to https://certifiio.readthedocs.io/en/latest/ does work.

**Comment by jhermann** [comment]
As an example: The requests docs still link to the old domain.
