### ISSUE TITLE
certifi.io webserver misconfigured?

### ISSUE THREAD

**Issue by paulmueller** [certifi/python-certifi#128]
I get a "403 forbidden" when trying to access https://certifi.io.
I would suggest/recommend migrating the documentation to readthedocs.io

**Comment by dbjock** [comment]
This issue is still ongoing. 
https://certifiio.readthedocs.io/en/latest/ redirects to https://certifi.io/en/latest/ which is "403 Forbidden"

**Comment by sigmavirus24** [comment]
Duplicate of https://github.com/certifi/certifi.io/issues/24
