### ISSUE TITLE
HTTP 403 error on https://certifi.io/ 

### ISSUE THREAD

**Issue by pombredanne** [certifi/python-certifi#132]
and also on https://certifiio.readthedocs.io/ that redirects there

**Comment by jaraco** [comment]
I noticed this when clicking Homepage from https://pypi.org/project/certifi.

**Comment by guerzon** [comment]
Hi there,

I just wanted to let you know that https://certifi.io/en/latest/ is still down.

Cheers.

**Comment by vyx-alex-willisson** [comment]
Still down

**Comment by jaraco** [comment]
This also looks to be a dupe of #128.

**Comment by sigmavirus24** [comment]
Duplicate of https://github.com/certifi/certifi.io/issues/24

**Comment by faiyeah** [comment]
It is still down till now

**Comment by hugovk** [comment]
Please see PR https://github.com/certifi/python-certifi/pull/145 for a fix.

**Comment by tucked** [comment]
This is still happening for me.
