### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by lmocsi** [certifi/python-certifi#133]
The bellow code produces "certificate verify failed" error, while the site opens fine in Firefox.
What can the problem be? (I have certifi==2020.6.20) 

    import requests
    
    url = 'https://net.cib.hu/ebroker/arfolyamok/cib_alapok_arfolyam/index?defaultLanguage=hungarian'
    content = requests.get(url).text

**Comment by alex** [comment]
The server is misconfigured and does not send a complete certificate chain: https://www.ssllabs.com/ssltest/analyze.html?d=net.cib.hu&latest
