### ISSUE TITLE
can you guy's provide cacert.pem Signature Algorithm by sha256WithRSAEncryption

### ISSUE THREAD

**Issue by kobe-tian** [certifi/python-certifi#134]
can you guy's provide cacert.pem Signature Algorithm by sha256WithRSAEncryption

your cacert.pem  Signature Algorithm by sha1WithRSAEncryption, it is not safe

thx

**Comment by alex** [comment]
Signature algorithms on root certificates are not used in validation, thus this isn't relevant.
