### ISSUE TITLE
Requesting CA Cert Bundle to be updated to the latest version released on July 22nd 2020

### ISSUE THREAD

**Issue by sfc-gh-hchaturvedi** [certifi/python-certifi#135]
New Ca Cert Bundle includes 2 new Microsoft Root CA Certificates that were added recently. These certs can potentially affect the ability to verify azure servers.  More details can be found here - https://docs.microsoft.com/en-us/azure/key-vault/general/whats-new#what-is-changing

**Comment by Lukasa** [comment]
What makes you think the new CA cert bundle contains these two roots? Nothing appears to have changed in Mozilla's certdata.txt.

**Comment by sfc-gh-hchaturvedi** [comment]
Apologies for the delayed response. We use curl's package that is based on Mozilla cert foundation as our trusted root store. 
(https://curl.haxx.se/docs/caextract.html) If you open the latest package and compare it with one older version you'll notice two new Microsoft certs added to the package. As I mentioned earlier these same certs are the ones that Microsoft announced in the post I linked earlier.

**Comment by sfc-gh-hchaturvedi** [comment]
Aah never mind. The cacert on cURL was recently updated however certifi I just noticed had been updated more proactively as soon as the cert was added in June this year. Sorry for the trouble and confusion. Closing this now.
