### ISSUE TITLE
Anaconda package is broken on Python 3.8 Linux

### ISSUE THREAD

**Issue by octachrome** [certifi/python-certifi#139]
Installing the latest Certifi using Conda in a Python 3.8 environment on 64-bit Linux installs something which is labeled as a Python 3.6 package:

    $ conda create -n certifi-test python==3.8 certifi
    ...
      certifi            pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3
    ...

    $ ls ~/anaconda/envs/certifi-test/lib/python3.8/site-packages | grep certifi
    certifi
    certifi-2020.6.20-py3.6.egg-info

The package is actually compatible with 3.8 - importing it causes no errors - so most people will not notice this problem. But the problem shows up when I try to build the Conda package for a project which has a dependency on Certifi. Conda complains with a confusing error message because it does not recognize that Certifi is installed, because the metadata is wrong:

    $ conda build ...
    ...
    Processing dependencies for xpressinsight==1.2.0
    Searching for certifi
    ...
    RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/certifi/

The problem goes away if I force our project to depend on an older version of Certifi, e.g., 2020.4.5.2. In fact, the problem only recently started happening, presumably when the updated Certifi was published to Anaconda.

Info about my system:

    $ uname -a
    Linux linux-build1.rhlappxpr16037 2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

    $ conda --version
    conda 4.8.1

    $ anaconda --version
    anaconda Command line client (version 1.7.2)

**Comment by Lukasa** [comment]
We do not publish certifi to anaconda. You’ll need to find the folks that do.

**Comment by jcmuel** [comment]
For those who are looking for the bug report in Anaconda: It can be found here:
https://github.com/ContinuumIO/anaconda-issues/issues/12148
