### ISSUE TITLE
GeoTrust Global CA removed in 2020.12.05

### ISSUE THREAD

**Issue by alyf80** [certifi/python-certifi#143]
Hello,

The following root CA was removed from 2020.12.05

    # Issuer: CN=GeoTrust Global CA O=GeoTrust Inc.
    # Subject: CN=GeoTrust Global CA O=GeoTrust Inc.
    # Label: "GeoTrust Global CA" 
    # Serial: 144470
    # MD5 Fingerprint: f7:75:ab:29:fb:51:4e:b7:77:5e:ff:05:3c:99:8e:f5
    # SHA1 Fingerprint: de:28:f4:a4:ff:e5:b9:2f:a3:c5:03:d1:a3:49:a7:f9:96:2a:82:12
    # SHA256 Fingerprint: ff:85:6a:2d:25:1d:cd:88:d3:66:56:f4:50:12:67:98:cf:ab:aa:de:40:79:9c:72:2d:e4:d2:b5:db:36:a7:3a

This certificate is part of a group that is handled specially by Mozilla, see [https://wiki.mozilla.org/CA/Additional_Trust_Changes#Symantec](https://wiki.mozilla.org/CA/Additional_Trust_Changes#Symantec), and is still required to verify a number of widely-used intermediate CAs, so dropping it is going to break things  (in my case, all calls to Apple APIs stopped working).

Debian had the same problem a few months ago: [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596)

**Comment by sigmavirus24** [comment]
Duplicate of #142

**Comment by alyf80** [comment]
> 
> 
> Duplicate of #142

Sorry, missed that.
