### ISSUE TITLE
Please add cert - GlobalSign GCC R3 DV TLS CA 2020

### ISSUE THREAD

**Issue by alecdhuse** [certifi/python-certifi#146]
GlobalSign recently forced reissue of many of their certificates to use a new intermediate certificate. That Intermediate certificate does not appear to be in the newest version of python-certifi.

The cert in question is names: GlobalSign GCC R3 DV TLS CA 2020
If can be obtained here: https://support.globalsign.com/ca-certificates/intermediate-certificates/domainssl-intermediate-certificates

Would it be possible to add this new Intermediate cert?

**Comment by alex** [comment]
We do not add intermediate certificates, we package the Mozilla root store.
