### ISSUE TITLE
CA Sectigo couldn't be verified

### ISSUE THREAD

**Issue by mahmoudrashwan** [certifi/python-certifi#148]
Any Domain Certificate issued by Sectigo Certificate Authority couldn't be verified. there is certificate chain for Sectigo like:
Sectigo (AAA)
  USERTrust RSA Certification Authority
    Sectigo RSA Domain Validation Secure Server CA
      $Any Domain Certificate Issued by Sectigo

I had to add the certificate chain manually into cacert.pem file located in certifi package, but every time I update my app release the file of cacert.pem replaced by original one. So I think Sectigo cert chain should be added.

**Comment by sigmavirus24** [comment]
We don't manage CAs, we merely use what Mozilla generates and package it for Python. This isn't the place to request this be added
