### ISSUE TITLE
Add instructions on how to update the certificate file locally

### ISSUE THREAD

**Issue by mfhepp** [certifi/python-certifi#150]
Sometimes, the certificate file from Mozilla is more current that the releases of this module.

In order to update the *.pem file locally, I wrote a short script that basically downloads the file from Mozilla and replaces the 'cacert.pem' file by that.

You can find the script here:

https://github.com/mfhepp/update_certifi_certificates

Alternatively, it would be good to include short instructions on how to update the file locally directly with the module.

**Comment by sigmavirus24** [comment]
No. See https://github.com/certifi/python-certifi/issues/72#issuecomment-776024458
