### ISSUE TITLE
Add configuration to use system certs instead

### ISSUE THREAD

**Issue by dwt** [certifi/python-certifi#166]
Hi there,

the recent problem with Letsencrypt and the expired certificate still in certifi brought to my attention that actually this package ingests a whole lot of certificates into each virtualenv that I use `requests` in.

That is a problem as I would rather use the system certificate store if I can help it, but `requests` (and others) pulls in these certificates as a dependency each time wether I want to or not.

Some (most?) distributions provide a patched version of `certifi` that users the system trust store instead, but for virtualenvs it's not simple to switch this.

I would like to propose:

- Either adding some sort of option / environment variable that can be set to switch this package to use the system trust store instead
- Or add enough hooks that another package can be created the mere installing of which switches `certifi` to use the system store. (There is already https://github.com/tiran/certifi-system-store which is close, but still requires calling shell tools after installation to actually switch. For this solution to work this should really be just an install, so merely adding the dependency to my apps list would be enough without adding another deployment step that is easy to miss).

Both of these solutions would solve the LetsEncrypt problem and would also allow to easily work around #162.

What do you think?

**Comment by Lukasa** [comment]
Upstream tools using certifi unconditionally without appropriate overrides is an issue to be filed on those tools, not on certifi. Certifi ships the Mozilla system trust store. It does nothing else. There is no plan to expand its functionality.
