### ISSUE TITLE
Project is languishing.

### ISSUE THREAD

**Issue by jaraco** [certifi/python-certifi#169]
This project appears to be languishing and nearly abandoned. Many PRs are sitting with no comments from the maintainers. The domain was allowed to expire and cause the web site to be down. Does the maintainers have a plan for ongoing maintenance?

**Comment by alex** [comment]
We did a new release 9 days ago.

The maintainers have never had any interest in anything besides packaging the Mozilla root store as a python package. Unfortunately no matter how many times we've repeated that, we continue to get bugs and feature requests with alternate premises.

**Comment by sigmavirus24** [comment]
Not to mention open and closed issues that are pinned that have happened in recent weeks.
