### ISSUE TITLE
long time session ends with "Could not find a suitable TLS CA certificate bundle"

### ISSUE THREAD

**Issue by fenchu** [certifi/python-certifi#185]
I connect via OIDC to a spring boot rest api, this works with a 60sec bearer access token I renew via keycloak whenever I get a 403
This works fine for ~19K sec (5.2Hours) then I got this:

```
Could not find a suitable TLS CA certificate bundle, invalid path: C:\dist\venvs\trk-fullstack-test\lib\site-packages\certifi\cacert.pem
```

If I restart it works fine:
```
requests==2.27.1
certifi==2021.10.8
```

Can an error in my connection has triggered looking for this pem file, but why not on startup?
how can I remedy those. this is a daemon that should always run.

**Comment by Lukasa** [comment]
This is unlikely to have anything to do with certifi. It has no meaningful logic: it will never update or move anything.
