### ISSUE TITLE
Remove CNNIC?

### ISSUE THREAD

**Issue by kevinburke** [certifi/python-certifi#19]
CNNIC issued an intermediate certificate to an organization that used it to issue valid certificates for many sites all over the Internet. In response, Mozilla and Chrome have both suspended accepting new CNNIC certificates: https://blog.mozilla.org/security/2015/04/02/distrusting-new-cnnic-certificates/

They are both accepting any certificates issued before April 1, 2015, but not any issued since then, until CNNIC applies and is re-admitted as a SSL vendor.

I was wondering if certifi had the ability to distinguish certificates issued by an authority and if so, if certifi should un-certify new CNNIC certificates.

**Comment by Lukasa** [comment]
Sadly, this is trickier than it looks.

OpenSSL does not provide us with the freedom to add these restrictions to its certificate validation steps. We can only have two states: do trust CNNIC, or don't trust CNNIC. I think we should move to "don't trust", but we can't just simply make that change.

We also have another problem with cross-signed root certificates, which I intend to think about at PyCon.
