### ISSUE TITLE
Use of deprecated `importlib.resources.path`

### ISSUE THREAD

**Issue by scop** [certifi/python-certifi#190]
`certifi.core` [uses `importlib.resources.path`](https://github.com/certifi/python-certifi/blob/51c3f2a6458205e1c9b3271f4f9ef82d4358b033/certifi/core.py#L14), which is deprecated in [importlib_resources 5.3.0](https://github.com/python/importlib_resources/blob/main/CHANGES.rst#v530) and thus [in Python 3.11](https://github.com/python/importlib_resources#compatibility), triggering a warning where enabled.

Seems the least intrusive fix that keeps backwards compatibility would be to add another `where()` implementation that uses [the `importlib.resources` `files()` API](https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy). Can understand if this feels a bit much at the moment, but if for nothing else, FFR.

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Comment by scop** [comment]
Considering the number of times this is repeatedly reported, I think it would be a good idea to pin one of these to make it prominently visible, like #132 and #72 already are.

Also, if an issue like this would be reported against a project in which I'm involved, I'd keep it open -- it _is_ an unresolved issue after all, even though there is no immediate intent to do anything about it; it's not going to go away/solve itself/by some 3rd party action automatically.
