### ISSUE TITLE
Add environment variable to override certificate bundle

### ISSUE THREAD

**Issue by Guerteltier** [certifi/python-certifi#200]
It would be nice to be able to set an environment variable `CERTIFI_OVERRIDE` to the path of a certificate bundle and have Certifi (and everything that uses Certifi) use that instead of the bundle included in Certifi.

**Comment by davisagli** [comment]
The whole point of `certifi` is to provide a specific bundle of CA certificates. If you want to use a different bundle, configure an `ssl.SSLContext` to load that bundle instead of using certifi.

**Comment by alex** [comment]
Yes, python already respects the `SSL_CERT_FILE` environment variable.
