### ISSUE TITLE
Versioning for releases in pypi has incorrect sorting

### ISSUE THREAD

**Issue by aebrahim** [certifi/python-certifi#208]
Looking through the git tags, these appear to have correctly sortable due to 2 digit days and months - e.g. `2022.12.07`. However, in the PYPI, the release version is `2022.12.7` which (a) doesn't match the tag and (b) will not sort cleanly to be clearly bigger than a release which may occur 3 days later.

This likely contributed to #207

To avoid these bugs, I believe it would make sense to switch to a CI-based release process to build wheels versioned to the tag, and upload them with https://github.com/marketplace/actions/pypi-publish - I am happy to assist with this task if required!

**Comment by alex** [comment]
What is the relationship between a CI based release process and this issue?

**Comment by aebrahim** [comment]
I believe the lack of a CI-based process caused this issue, because the tag versions are correct, but the PYPI ones are not - so an automated CI-based release process based on the tag numbers would result in correct versions in PYPI.

**Comment by alex** [comment]
I believe the PyPI ones are different because software automatically normalized them, not because of a typo or anything.

**Comment by aebrahim** [comment]
Oh I see - you are 100% correct https://github.com/pypa/setuptools/issues/302
