### ISSUE TITLE
Mismatch between Pip version and Tag released

### ISSUE THREAD

**Issue by kush-jain** [certifi/python-certifi#212]
On pip, latest version released is `2022.12.7`, whereas latest tag released on github is `2022.12.07`.

This is affecting security pipelines, since CVE DB is searching for `2022.12.07` as minimum tag, but finding `2022.12.7` as the installed package.

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

Duplicate of #208 and many others
