### ISSUE TITLE
Can't Install through pip

### ISSUE THREAD

**Issue by Muhammad-Ahsan-Rasheed** [certifi/python-certifi#213]
Hi,

I was trying to install the certifi package through pip but get this error:

```
Could not fetch URL https://pypi.org/simple/certifi/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retri
es exceeded with url: /simple/certifi/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement certifi (from versions: none)
ERROR: No matching distribution found for certifi
```

Any help in this regards is appreciated.

Regards,

**Comment by alex** [comment]
Did you read the error message?

> Can't connect to HTTPS URL because the SSL module is not available.

Your Python installation doesn't have an `ssl` module. This has nothing to do with certifi, you wouldn't be able to install anything.
