### ISSUE TITLE
Inconsistent installation version

### ISSUE THREAD

**Issue by Tiny123445** [certifi/python-certifi#215]
When I use command: "pipenv install --keep-outdated certifi==2022.12.07" to install certifi, the installed version is 2022.12.7, why the installed version number is different with choose version?

**Comment by Tiny123445** [comment]
pipenv install --keep-outdated  certifi==2022.12.07
Installing certifi==2022.12.07...
✔ Installation Succeeded


cmd: pipenv graph | grep certifi
  - certifi [required: Any, installed: 2022.12.7]
    - certifi [required: >=2017.4.17, installed: 2022.12.7]
    - certifi [required: >=2017.4.17, installed: 2022.12.7]
    - certifi [required: >=2017.4.17, installed: 2022.12.7]
Why the number is different?

**Comment by sigmavirus24** [comment]
Duplicate #208
