### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [certifi/python-certifi#223]
The last release was in December 2022. A few months have passed and certs updated in-between. Wondering if a new release of this package could be produced? Thanks for all of your hard work here! 🙏

**Comment by alex** [comment]
Is there a particular update you're expecting? I don't see changes to certdata files in Firefox since December: https://hg.mozilla.org/mozilla-central/log/tip/security/nss/lib/ckfw/builtins/certdata.txt

**Comment by jakirkham** [comment]
Looks like this was recently done. Closing...
