### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [certifi/python-certifi#238]
Is it possible next time on release new version make the github release to have entry on https://github.com/certifi/python-certifi/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by alex** [comment]
Our answer here is the same as for pyca/cryptography:

> If you're interested in monitoring for new releases, PyPI offers an RSS feed for each package that can be used. Since we do not rely on any of the features of github releases, I think we're unlikely to use it purely for notifications.

**Comment by jaraco** [comment]
FWIW, I use an [automated procedure](https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58) to cut tagged commits to both PyPI and GitHub. Feel free to re-use that routine if you like.

**Comment by kloczek** [comment]
Thank you very much 👍
