### ISSUE TITLE
Include license files in the pypi tarball

### ISSUE THREAD

**Issue by williamjmorenor** [certifi/python-certifi#24]
Hi I am packaging python-certifi in Fedora and I want to ask about include the license file in the pypi tarball please

Regards

**Comment by sigmavirus24** [comment]
Good catch. That should be there

**Comment by Lukasa** [comment]
Yup, that's easily done. =)

**Comment by sigmavirus24** [comment]
Actually, that is already in the tarball.

```
~ pip install -d. certifi --no-use-wheel
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting certifi
  Downloading certifi-2015.04.28.tar.gz (370kB)
    100% |████████████████████████████████| 372kB 641kB/s
  Saved ./certifi-2015.04.28.tar.gz
Successfully downloaded certifi
~ tar xf certifi-2015.04.28.tar.gz
~ ls cer
certifi-2015.04.28/        certifi-2015.04.28.tar.gz
~ ls certifi-2015.04.28
LICENSE           PKG-INFO          certifi/          setup.cfg
MANIFEST.in       README.rst        certifi.egg-info/ setup.py*
```

I did notice, however, that the generated wheel doesn't seem to have this information. @williamjmorenor were you talking about the wheel file? If not, are you using the right version of certifi's tarball? The inclusion of the LICENSE file is determined b y https://github.com/certifi/python-certifi/blob/master/MANIFEST.in

**Comment by sigmavirus24** [comment]
It's been almost a year without any further information about this. Closing as inactive.
