### ISSUE TITLE
globalsign GCC R3 DV TLS CA 2020 not trusted

### ISSUE THREAD

**Issue by Adarajames** [certifi/python-certifi#249]
Hi
I have no idea about what any of this means, so please be gentle and put any reply into idiot proof words! ;) 

Since a citrix update last week, I have been unable to sign into my work VPC via my home / camper wifi, can get logged in and things open and then everything just freezes.  Has been tried on multiple machines so it's not machine based; I can also log in and run everything OK if use phone as a hot spot, but not when connected to internet via wifi or ethernet plugged into home / van broadband.
Searching the issue that comes up on an error message gave me this site with the above title matching the error message I get when look at certificate errors.
Can anyone please help?
![SSL error](https://github.com/certifi/python-certifi/assets/147433970/cb57c28c-791a-4725-a430-adec4b98515a)

**Comment by alex** [comment]
This project is a python package containing the Mozilla root store.

Are you even using Python?
