### ISSUE TITLE
extract system trust roots on OS X

### ISSUE THREAD

**Issue by glyph** [certifi/python-certifi#25]
Homebrew has a recipe for doing this; it involves running the `security` tool on the command line.

**Comment by dreid** [comment]
https://github.com/Homebrew/homebrew/blob/8ba134eda537d2cee7daa7ebdd9f728389d9c53e/Library/Formula/openssl.rb#L106-L128

**Comment by Lukasa** [comment]
Good idea. I assume the goal here is to have an extra bundle that uses the system roots? Do we build that bundle at install time? Import time? Where do we save it to file?

**Comment by dreid** [comment]
Homebrew does it at post_install OpenSSL, so install time for certifi seems reasonable? I think uninstall/reinstall is a reasonable strategy for keeping it up to date. This probably interacts badly with the wheel cache though.

**Comment by glyph** [comment]
My suggestion would be to update it based on mtime and *not* do it at install time; if the mtime of either of those two pathnames has changed, re-generate the cached version.  This should happen rarely, and if you do it every time, certifi will always be up to date with the system.

**Comment by sigmavirus24** [comment]
Yeah install time isn't ideal in the world where wheels are the primary distribution.

**Comment by Lukasa** [comment]
@dstufft Is it safe to assume that we can edit files inside the wheel distribution? That is, can I write the file into the wheel at runtime, or update an already existing file? Should I ever expect that the wheel or sdist will not have a writeable directory?

**Comment by dstufft** [comment]
You mean once it's installed?

**Comment by Lukasa** [comment]
Yes

**Comment by dstufft** [comment]
Once it's installed it's no longer a wheel, it's just an installed package. I would not expect to have write access at runtime (see below), I would instead use common data directories on different OSs like:

* OSX: ``~/Library/Caches/certifi``.
* Linux: ``~/.cache/certifi``.
* Windows: ??? The non roaming profile thing.

```console
$ sudo pip install certifi 
$ python -c "import certifi"
```

**Comment by Lukasa** [comment]
Awesome, that makes sense. I think we can make this work using those standard storage locations.

This seems like a great idea, I'll get started on it fairly shortly.

**Comment by sigmavirus24** [comment]
:+1: to @Lukasa

**Comment by alex** [comment]
Why bother doing it at install time? Why not every time you ask for the path it run that command and put it in a new location on disk?

(Possibly with internal caching for some short period like 1 minute)

**Comment by Lukasa** [comment]
@alex I worry about the number of cases where we just repeatedly call `certifi.where()`, which would cause a lot of extra computation. I'd want to avoid repeatedly doing that computation, or even doing it more frequently than absolutely necessary (e.g. once a day).

**Comment by alex** [comment]
@Lukasa is your concern that a given Python `pid` would call `certifi.where()` many times, or that many different processes would call it many times?

**Comment by Lukasa** [comment]
Both. Certainly requests potentially calls `certifi.where()` many times.

**Comment by alex** [comment]
For the single process case, you can easily store the path to the temporary
file you created in-memory and only re-trigger it every so often.

For the multi-process use case it's more complicated, instead of a
temporary file you can put certifi's generated bundle at a predicate
location and update based on mtime.

On Sun, Aug 9, 2015 at 5:50 PM, Cory Benfield <notifications@github.com>
wrote:

> Both. Certainly requests potentially calls certifi.where() many times.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/certifi/python-certifi/issues/25#issuecomment-129248163>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by Lukasa** [comment]
I guess I'm wondering whether it's worth doing the update that regularly, or whether we should say something more like 'process startup, plus once each day thereafter'.

**Comment by alex** [comment]
To step back: I don't feel strongly about any of the implementation
details. I do believe that requiring someone to reinstall in order to
refresh their trust stores is a very bad idea, particularly given
virtualenv proliferation and lack of clear versioning means that people are
likely to have out of date trust stores.

On Sun, Aug 9, 2015 at 5:58 PM, Cory Benfield <notifications@github.com>
wrote:

> I guess I'm wondering whether it's worth doing the update that regularly,
> or whether we should say something more like 'process startup, plus once
> each day thereafter'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/certifi/python-certifi/issues/25#issuecomment-129252251>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by glyph** [comment]
@Lukasa - I don't understand. Are you concerned about the startup cost of `stat()`ing three files to check their mtime?

**Comment by glyph** [comment]
To be clear, here's what you have to do:

- check the mtime of `/Library/Keychains/System.keychain`
- check the mtime of `/System/Library/Keychains/SystemRootCertificates.keychain`
- check the mtime of `~/Library/Caches/certifi/OS-bundle.pem`

If either of the first 2 is greater than that of the 3rd, regenerate it.

**Comment by Lukasa** [comment]
@glyph @alex Sorry, this is getting mired down.

I don't care about the *startup* cost of `stat`-ing three files. I don't care about the once-per-day cost of `stat`-ing those files either. I'm *not* wild about the cost of `stat`-ing three files every single time you make a web request.

I am totally happy to cache the responses to this and check on startup and then every *n* seconds, where *n* is some vaguely reasonable number. I was just wanting to confirm that my fears are well-grounded: for example, people may believe it's totally reasonable to do this check each time `certifi.where()` (or whatever this ends up being called) is invoked, and that users should do the caching themselves.

**Comment by glyph** [comment]
@Lukasa - since we're only talking about OS X, pretty much any update to the certificate bundles is going to require a reboot, because it's going to come with a security update, which is an OS update.  So checking once per process lifetime is more than enough.

**Comment by Lukasa** [comment]
Seems fair. Ok, that's a good policy.

**Comment by ssbarnea** [comment]
Any updates on this issue? The SSL certificate store issue on MacOS is still a big pain for any Python user that is not using the system Python (which I assume is a **lot**)

**Comment by Lukasa** [comment]
This is ongoing: please see python-ideas and the Security SIG mailing list.

**Comment by ssbarnea** [comment]
Thanks. Adding link to archive https://mail.python.org/mailman/listinfo/security-sig

**Comment by alex** [comment]
In the 6 years since this issue was originally filed, certifi has moved to more clearly existing only as a way to package the Mozilla trust store, not as a general purpose trust store interface, so I'm going to close this.
