### ISSUE TITLE
Question about license python-certifi used

### ISSUE THREAD

**Issue by zhengliuer** [certifi/python-certifi#259]
Hi, when creating a conda python environment, certifi is installed. When checking the license, here https://anaconda.org/conda-forge/certifi says it's ISC(in conda's conda-meta, certifi*.json also shows ISC), but in the repo, it says MPL2.0. Which one should I use?

Thanks!
Zheng

**Comment by alex** [comment]
It's MPL2.0; this project is a redistribution of Mozill'a trust store. Conda's metdata is wrong.

**Comment by zhengliuer** [comment]
Thanks a loy

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Alex Gaynor ***@***.***>
发送时间: Friday, December 29, 2023 10:06:34 PM
收件人: certifi/python-certifi ***@***.***>
抄送: Zheng Liu ***@***.***>; Author ***@***.***>
主题: Re: [certifi/python-certifi] Question about license python-certifi used (Issue #259)


It's MPL2.0; this project is a redistribution of Mozill'a trust store. Conda's metdata is wrong.

―
