### ISSUE TITLE
GoDaddy Certificate Bundles - G2 Missing from cacert.pem

### ISSUE THREAD

**Issue by alpeshv** [certifi/python-certifi#263]
GoDaddy Secure Server Certificate (Intermediate Certificate) - G2 ([gdig2.crt.pem](https://certs.godaddy.com/repository/gdig2.crt.pem)](https://certs.godaddy.com/repository) is missing from cacert.pem. This is making `requests.get(...)` throw _Unable to get Local Issuer Certificate_ exception. I have added missing part in my local cacert.pem to make it work but it will be useful to add it in repo so that it will benefit others who will need to call an api which uses Go Daddy G2 CA.

I have added my updated [cacert.pem.txt](https://github.com/certifi/python-certifi/files/14088097/cacert.pem.txt) for your reference. (It is renamed as .txt in order to upload it here)

**Comment by alex** [comment]
Why do you believe this CA should be in the trust store?

**Comment by alpeshv** [comment]
@alex I have updated the certificate name. Its intermediate certificate which is missing. After investigating it further, I guess you are right that cacert.pm should not have any intermediatory certificates. They should be provided by web app/api.
