### ISSUE TITLE
Not able to upgrade version for certifi

### ISSUE THREAD

**Issue by ayushi-singhal** [certifi/python-certifi#272]
I've two files requirements.in listing all dependencies and versions, and another is requirements.txt which is created after compiling requirements.in and is used to install dependencies.

certifi version is 2021.10.8 and mentioned in requirements.txt file. I am trying to upgrade the transitive dependencies like sentry, requests, etc in requirements.in file and but the certifi version is not changing in requirements.txt and virtual env.

I am not sure what steps or process I am missing here.

I appreciate the help, Thanks.

This is very very urgent for my project.

**Comment by alex** [comment]
You're not describing any bug in certifi, you're asking for basic python packaging support. We're not able to provide support for other python packaging tools here.
