### ISSUE TITLE
old_root.pem and weak.pem

### ISSUE THREAD

**Issue by benoitc** [certifi/python-certifi#30]
How are generated these files? They may be useful for erlang users as well. Any hint on how to generate them would be helpful :)

**Comment by Lukasa** [comment]
`old_root.pem` was, unfortunately, generated by hand. This required that I go through *every* Mozilla bug report relating to 1024-bit roots and determine what roots were removed, and then add them to that file. It was...painful.

`weak.pem` is created simply be running `cat cacert.pem old_root.pem > weak.pem`, and I regenerate it each time I update `cacert.pem`.

Feel free to simply take `old_root.pem` from here!

**Comment by benoitc** [comment]
@Lukasa thanks!

So I guess this line is OK?
https://github.com/certifi/erlang-certifi/commit/c0e9845608c17a574d4e890fd8e3ea0c8806ebd1#diff-70ba2f62ce585deae5af9ae7c952f4c6R46

**Comment by Lukasa** [comment]
LGTM.
