### ISSUE TITLE
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

### ISSUE THREAD

**Issue by tardelivinicius** [certifi/python-certifi#303]
Hello!

One of my clients sent me an updated domain certificate on 08/16/2024, and after applying it, my entire Django project stopped working. I investigated the issue and found out about certifi. I analyzed the cacert.pem file and noticed that it does not include the keys for this certificate, possibly because it's new. Is there any forecast for the 2024.08 update? Temporarily, I edited the file and added the key, and I had to set verify in my requests for it to work. However, I can't work like this since I use CI/CD and generate the ENV directly from my action.

Certificate Information:
GeoTrust TLS RSA CA G1

**Comment by alex** [comment]
"GeoTrust TLS RSA CA G1" is an intermediate, and thus not expected to be present in a trust store. It was issued by "DigiCert Global Root G2" which is present in certifi.

It sounds like you did not configure your intermediates correctly on your server. See https://whatsmychaincert.com/ for more details
