### ISSUE TITLE
Inquiry about Commercial Use of Certifi

### ISSUE THREAD

**Issue by Mai0313** [certifi/python-certifi#315]
I am developing a commercial software application that utilizes the `requests` library, which in turn depends on `certifi`. I understand that `certifi` is licensed under the Mozilla Public License 2.0 (MPL 2.0).

I would like to confirm whether it is permissible to use `certifi` in a commercial product under the following conditions:
1. We will not modify the original source code of `certifi`.
2. We will not distribute `certifi` separately; it will only be included as a dependency within our software.

Could you please confirm if this usage complies with the MPL 2.0 license terms?
I have checked the [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) before asking this question; I just wanna confirm it.

**Comment by alex** [comment]
The terms of the MPL are publicly available, for guidance on their meaning you can consult a lawyer or refer to a public resource such as https://choosealicense.com/licenses/mpl-2.0/
