### ISSUE TITLE
Proposal: Refactor `certifi` to Embed Data and Code in a Single Python File

### ISSUE THREAD

**Issue by CDU-Ge** [certifi/python-certifi#324]
#### Summary
This proposal suggests refactoring the `certifi` package to embed certificate data directly within the Python file. This approach aims to simplify dependency management and make code changes more noticeable.

#### Motivation
1. **Parsing Issues**: In some cases, parsing certificates from external files can lead to issues. Embedding the certificate data directly in the Python file can mitigate these problems.
2. **Dependency Complexity**: Relying on external files increases complexity. By embedding the data, we reduce the number of dependencies.
3. **Code Change Visibility**: Changes in code are more likely to be noticed than changes in data files. Embedding the data ensures that any modifications are more apparent.
4. **Cross-System Compatibility**: Different file paths across systems can cause issues, especially in multi-language environments. A more user-friendly approach is to allow writing to the package's file location to maintain compatibility with previous versions. 
5. This approach might also be safer ?

#### Proposed Changes
- Embed the certificate data directly within the `certifi.py` file.
- Modify the `where` function to handle the embedded data and write to the package's file location if necessary.

#### Example
Here is an example of the refactored `certifi.py` file:

```python
# -*- coding: utf-8 -*-

import os

_CA_CONTENT = """
Very Loooooooooooooooooooooooooooooong
"""

def where():
    if os.environ.get("CERTIFI_CA_PATH"):
        _path = os.environ.get("CERTIFI_CA_PATH")
    else:
        # Need do more
        _path = os.path.join(os.path.dirname(__file__), "cacert.pem")
    # tempdir ?
    # create the directory if it does not exist
    _dir = os.path.dirname(_path)
    if not os.path.exists(_dir):
        os.makedirs(_dir, exist_ok=True, mode=0o755)
    if not os.path.exists(_path):
        with open(_path, "w") as f:
            f.write(_CA_CONTENT)
        # read-only
        os.chmod(_path, 0o444)
    return _path

def contents():
    return _CA_CONTENT
```

#### Benefits
- **Simplified Dependency Management**: Reduces the need for external files.
- **Increased Visibility**: Changes to the certificate data are more likely to be noticed.
- **Reduced Parsing Issues**: Embedding the data directly can prevent parsing issues.
- **Cross-System Compatibility**: Writing to the package's file location ensures compatibility across different systems and environments.

#### Drawbacks
- **File Size**: Embedding large amounts of data can increase the file size.
- **Maintenance**: Updating the certificate data requires modifying the Python file.

#### Conclusion
Embedding the certificate data within the `certifi.py` file simplifies dependency management and increases the visibility of changes. This approach can reduce parsing issues, make the codebase easier to maintain, and ensure cross-system compatibility.

**Comment by alex** [comment]
I do not understand the motivations you have indicated for this. For example, I have no idea what it means that an external file can cause parsing issues.

Before we can even begin considering this, you need to articulate the motivation much more clearly and with more detail.

Further, because the primary entrypoint is `where()`, which returns a path on disk (which is, in turn, motivated by the stdlib `ssl` module's APIs), there will always need to be an on-disk path, and so this seems like it will almost certainly always involve more complexity of needing to write out a temporary file to disk.

**Comment by CDU-Ge** [comment]
> I do not understand the motivations you have indicated for this. For example, I have no idea what it means that an external file can cause parsing issues.
> 
> Before we can even begin considering this, you need to articulate the motivation much more clearly and with more detail.
> 
> Further, because the primary entrypoint is `where()`, which returns a path on disk (which is, in turn, motivated by the stdlib `ssl` module's APIs), there will always need to be an on-disk path, and so this seems like it will almost certainly always involve more complexity of needing to write out a temporary file to disk.

I will elaborate on my core intention in detail:

I hope the temporary CA certificate path can be more controllable, or in other words, it can be defined by the user to the desired location.

I do this mainly for the following reasons:
In a multilingual environment, this path may contain non-ASCII characters, and for some C libraries (such as libcurl), they will be unable to locate the file. A fixed, minimalist, or user-definable location will greatly alleviate this issue.

We leave the decision of how to solve the problem to the developers, allowing them to choose the appropriate location.

Storing the certificate file as a file within the package introduces unnecessary complexity; 
for any system, returning a variable from memory rather than reading from a file will result in fewer issues.

Regarding writing to a temporary directory, the responsibility now lies with the developer. 

Embedding the certificate within the code might always ensure the integrity and security of the certificate? 

All of this work can be automated through scripts, and we don't need to manually synchronize changes to the certificate content with the code.

I noticed that the existing code needs to handle Python version issues, but by doing so, we might be able to ignore it, as we currently only rely on `open` and `os.chmod` (without needing `pathlib`).

Fewer dependencies might reduce this issue, and this means that even if `where` doesn't work properly, our `contents` will always be functional.

Additionally, at this point, it might be possible to accomplish everything with just a single Python file rather than needing a package.

Note: To be honest, my motivations are only two: specifying the path for custom CA certificates and processing a single file. The rest are suggestions I made to the best of my ability to facilitate the proposal's success, although I assure you they are genuine.

**Comment by sigmavirus24** [comment]
> Note: To be honest, my motivations are only two: specifying the path for custom CA certificates and processing a single file. The rest are suggestions I made to the best of my ability to facilitate the proposal's success, although I assure you they are genuine.

You should not be trying to edit this package to add custom CAs. The MPL is quite clear about the terms of the license. You are also almost certainly introducing an opportunity to cause something consuming your modified bundle to trust something you didn't intend to trust and thus increasing your attack surface. 

To be clear, none of your reasoning is valid as far as this project is concerned. If you had checked closed issues first you would have seen that. 

Instead you've wasted time talking about a non-issue of multilingual environments (which seems to my nose to be LLM hallucinations and blather), a non-issue of simplifying the package (it's already quite simple), and allowing someone to specify the path to the file (guess what, if you put your custom CAs in a path, every HTTP library will use that path if you ask it to). None of this has been productive or worthwhile

**Comment by CDU-Ge** [comment]
> > Note: To be honest, my motivations are only two: specifying the path for custom CA certificates and processing a single file. The rest are suggestions I made to the best of my ability to facilitate the proposal's success, although I assure you they are genuine.
> 
> You should not be trying to edit this package to add custom CAs. The MPL is quite clear about the terms of the license. You are also almost certainly introducing an opportunity to cause something consuming your modified bundle to trust something you didn't intend to trust and thus increasing your attack surface. 

I apologize if I was misunderstood, but I do not anticipate any actions that would modify the CA certificate. All I expect is that users have the opportunity to edit the content returned by 'where()'.

> 
> To be clear, none of your reasoning is valid as far as this project is concerned. If you had checked closed issues first you would have seen that. 
> 
> Instead you've wasted time talking about a non-issue of multilingual environments (which seems to my nose to be LLM hallucinations and blather), a non-issue of simplifying the package (it's already quite simple), and allowing someone to specify the path to the file (guess what, if you put your custom CAs in a path, every HTTP library will use that path if you ask it to). None of this has been productive or worthwhile 

If the project is located in a location with a non-ASCII path, the path provided by 'where' would be nearly unusable for libcurl, as it lacks the capability to handle such paths.

Additionally, I wish to conceal from the end user the fact that a CA certificate is involved, especially since the certificate is dynamically generated rather than pre-edited.I am not sure if I have expressed myself clearly.

**Comment by sigmavirus24** [comment]
> I apologize if I was misunderstood, but I do not anticipate any actions that would modify the CA certificate. All I expect is that users have the opportunity to edit the content returned by 'where()'.

Which is it? Are you modifying the trust bundle distributed by this library or not? You talk about modifying the contents, regardless of whether you intend to remove or add, you're breaking the contract of this library. Regardless we're not going to enable that for you. 

> If the project is located in a location with a non-ASCII path, the path provided by 'where' would be nearly unusable for libcurl

PyCurl has zero issues with the paths returned by certifi. If you're writing C that you expect will use the output of this library somehow, that is not a supported use case as far as I'm concerned. There are many other ways to get and use a trust bundle. 

> Additionally, I wish to conceal from the end user the fact that a CA certificate is involved, especially since the certificate is dynamically generated rather than pre-edited

This is terrifying and I will absolutely never support your use case for exactly this reason. The amount of malicious behavior that can be enabled with this is too large. I strongly urge you to change your design.

**Comment by CDU-Ge** [comment]
> Which is it? Are you modifying the trust bundle distributed by this library or not? You talk about modifying the contents, regardless of whether you intend to remove or add, you're breaking the contract of this library. Regardless we're not going to enable that for you.

I did not modify the content; in fact, this is precisely the purpose of my proposal. If this is not done, I will have no choice but to remove it from my system dependencies.

I think we might have misunderstood each other. Do you think I want to add custom certificates or modify the content of certificates? No, I absolutely do not want to do that, and I want to avoid it.

I don't quite understand why modifying the `where` content would cause such strong opposition. If possible, I would even prefer this address to be a virtual file location, such as /{hash}.

You might think I'm compromising potential security, but I want to make everything more secure.

> PyCurl has zero issues with the paths returned by certifi. If you're writing C that you expect will use the output of this library somehow, that is not a supported use case as far as I'm concerned. There are many other ways to get and use a trust bundle.

> This is terrifying and I will absolutely never support your use case for exactly this reason. The amount of malicious behavior that can be enabled with this is too large. I strongly urge you to change your design.

I don't understand why this worries you so much, and this act doesn't seem to me to have any disruption to the chain of trust.
The purpose of this is to avoid any potential modifications to the certificate and to ensure that the certificate is read-only, and that it is regenerated from hard-coded code each time.
Imagine why not design it as a memory-mapped file and expose it as a read-only path.
I think this enhances tampering resistance and reduces the attack surface. And this is combined with the first point to do dynamic loading.
If there is a problem with these, please point them out, and if it is because of my stupidity, I am sorry for myself.
