### ISSUE TITLE
Trove classifiers are missing from PyPI page

### ISSUE THREAD

**Issue by cclauss** [certifi/python-certifi#44]
https://github.com/certifi/python-certifi/blob/master/setup.py#L58-L60 Certifi supports Python 3 but these "trove classifiers" are missing from [Certifi PyPI record](https://pypi.python.org/pypi/certifi). This has caused Certifi to go from green to red on the [Python 3 Wall of Superpowers](https://python3wos.mybluemix.net/).

**Comment by Lukasa** [comment]
Fixed, thanks. =)

@sigmavirus24 Why do the trove classifiers keep getting lost every time I twine upload a package?

**Comment by sigmavirus24** [comment]
@Lukasa what version of twine are you using? We upload the wheels first (since 1.5.0 ish?) so you should check the wheels you're building and uploading to make sure the wheel metadata is correct (which includes trove classifiers)

**Comment by Lukasa** [comment]
@sigmavirus24 Why wouldn't the wheel metadata be correct?

**Comment by sigmavirus24** [comment]
@Lukasa that's not entirely obvious to me, frankly. Let me toy around with this.

**Comment by sigmavirus24** [comment]
Using twine 1.8.0 this works just fine: https://test.pypi.org/project/certifi/ (uploading wheel and sdist simultaneously). I generated the wheel on Python 2.7 with setuptools 25.1.6 and wheel 0.29.0. What versions are you running @Lukasa?

**Comment by Lukasa** [comment]
```
args==0.1.0
clint==0.5.1
invoke==0.13.0
pkginfo==1.3.2
requests==2.10.0
requests-toolbelt==0.7.0
twine==1.7.4
```

So it's possible that there's just something weird going on here. Let's wait for the next release to see if this happens again.

**Comment by Lukasa** [comment]
So I just noticed that the Makefile actually didn't use Twine. So maybe this is a setuptools problem, not a Twine problem.

See 494d8a3a3260a178ae7a585d51a63ad98fa8e283.

**Comment by sigmavirus24** [comment]
Yeah, so this is probably not a twine issue then. =/
