### ISSUE TITLE
Drop support for `old_where`

### ISSUE THREAD

**Issue by alex** [certifi/python-certifi#53]
1) 1024-bit roots have only gotten more dangerous since we started this deprecation process
2) OpenSSL 1.0.1 has had this patch backported, including to distros like Ubuntu
3) OpenSSL 1.0.1, 1.0.0, and 0.9.8 are now EOL by upstream

The combination of all these factors means that keeping it around is more risk than is necessary.

To do this deprecation I recommend modifying `old_where` to simply return `where()` and emitting a warning. It can then be removed after the appropriate period.

**Comment by Lukasa** [comment]
I am, *in general*, warm towards doing this However, in practice I'm still not certain about it. Do we have an idea of what the state is in Red Hat based distributions?

**Comment by alex** [comment]
Great question, I do not. If you can remind me the easiest way to test, I'll go ahead and do so in some docker containers

**Comment by alex** [comment]
Ok, both CentOS 6 and 7 fail at `requests.get("https://google.com", verify=certifi.where())`, which is very disappointing. Sad to see a distro nominally aimed at security conscious enterprises holding the ecosystem back.

**Comment by Lukasa** [comment]
Yeah, it would be good if we could find a Red Hat engineer who knows why this decision was made.

**Comment by alex** [comment]
CC: @tiran

**Comment by alex** [comment]
Looks like:

- https://bugzilla.redhat.com/show_bug.cgi?id=1276310
- https://bugzilla.redhat.com/show_bug.cgi?id=1367434

Are the two relevant upstream issues.

**Comment by alex** [comment]
So, this is fixed in RHEL7 now; RHEL 6 is still SOL. 

It's worth noting that at this point requests users can address this with `pip install requests[security]` since it provides a nice OpenSSL.

What do you think @Lukasa ?

**Comment by Lukasa** [comment]
For the moment I’m inclined to say it provides pretty minimal maintenance burden to keep it around, so I’m a bit inclined to err on the side of inaction here. What do you think @alex?

**Comment by alex** [comment]
Maybe we should pick a point at which it'll be removed. First release of 2018?

**Comment by Lukasa** [comment]
Sure, that works for me.

**Comment by sigmavirus24** [comment]
Thank you for driving this, @alex.
