### ISSUE TITLE
domain certifi.io seems to have expired

### ISSUE THREAD

**Issue by ploxiln** [certifi/python-certifi#56]
Links to the Certifi website seem to be broken in various places (requests website, pypi) because certifi.io no longer resolves anything.

**Comment by alex** [comment]
`www.certifi.io` appears to have working DNS, but what it points at isn't listening.

**Comment by ploxiln** [comment]
I get NXDOMAIN for `www.certifi.io`. It appears to me that `certifi.io` has dnsimple nameservers but no other records.

**Comment by ploxiln** [comment]
I couldn't get command-line whois to work, but found http://www.nic.io/cgi-bin/whois which says certifi.io expires 2017-04-14 (so not yet, but suspicious...)

**Comment by Lukasa** [comment]
Yup, this is the result of a disagreement between us and out hosting provider over billing: so far @kennethreitz hasn't had time to re-host the site.

**Comment by mr-c** [comment]
FYI: Website is back up

**Comment by ploxiln** [comment]
It does appear to be. Now expires 2018-04-14

**Comment by kennethreitz** [comment]
thanks!

**Comment by kennethreitz** [comment]
Set to auto-renew :)
