### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jayfk** [certifi/python-certifi#57]
Is there a changelog available for `certifi`?

**Comment by sigmavirus24** [comment]
What would be included in the Changelog? The date that we use for the package version is the date that we've updated the certificate bundle from Mozilla.

**Comment by jayfk** [comment]
I'm looking at noteworthy changes like the one mentioned in the readme:

> Browsers and certificate authorities have concluded that 1024-bit keys are unacceptably weak for certificates, particularly root certificates. For this reason, Mozilla has removed any weak (i.e. 1024-bit key) certificate from its bundle, replacing it with an equivalent strong (i.e. 2048-bit or greater key) certificate from the same CA. Because Mozilla removed these certificates from its bundle, certifi removed them as well.

or mozilla dropping wosign: https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

or a distrust of Symantec issued certs in the future (once that happens): https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/eUAKwjihhBs%5B26-50%5D

**Comment by Lukasa** [comment]
@jayfk Well, I should note that we still trust WoSign and will still trust Symantec. In these instances Mozilla is using "graduated" trust; that is, those CAs are partially trusted. We cannot express that in certifi. 

For that reason, all the changelog would contain is which CAs are added and removed. We could do that, but I'm not sure how valuable that would be.

**Comment by sigmavirus24** [comment]
> For that reason, all the changelog would contain is which CAs are added and removed. We could do that, but I'm not sure how valuable that would be.

Right. I doubt most people who would be using a service like pyup/requires.io/etc. really care about that information. In fact, I doubt any of our consumers are interested in that.

**Comment by jayfk** [comment]
I'm convinced! :)

**Comment by jayfk** [comment]
> Right. I doubt most people who would be using a service like pyup/requires.io/etc. really care about that information. In fact, I doubt any of our consumers are interested in that.

Oh, I really wouldn't say that. I've had the pleasure to meet a lot of people who vet the dependencies they are using very very carefully.

**Comment by sigmavirus24** [comment]
> Oh, I really wouldn't say that. I've had the pleasure to meet a lot of people who vet the dependencies they are using very very carefully.

I was imprecise in my language. Let me expand a little. Certifi is a very odd Python package. We have a stable and rather concrete API that will not change. Beyond that, the changes to the certificate bundle are often more detail than the users of Certifi care about. As a consequence, I doubt users of Certifi and pyup/requires.io/etc. would be as concerned about those changes as they are that the package will continue to not break the public API. The specifics of bundle changes are often only interesting to a narrow subsection of our users.
