### ISSUE TITLE
Google certificate is not accepted

### ISSUE THREAD

**Issue by throwable-one** [certifi/python-certifi#60]
With latest requests and certifi try to open https://www.google.com with requests
It says CERTIFICATE_VERIFY_FAILED

I am using recaptcha2 and it is broken because of that

**Comment by alex** [comment]
What OS/OpenSSL version are you using?

This is almost certainly a duplicate of https://github.com/certifi/python-certifi/issues/26

**Comment by sigmavirus24** [comment]
I agree with @alex

**Comment by Lukasa** [comment]
As do I.

**Comment by throwable-one** [comment]
```
$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
```

Thanks for your answer, I now see it is duplicate of #26
