### ISSUE TITLE
Entrust Certificate Authority - L1K not in cacert.pem

### ISSUE THREAD

**Issue by dalevova** [certifi/python-certifi#67]
Hi,

I can open a site in Firefox browser: https://www.cdta.org/ but cannot download a file from it using python 2.7, because a certificate authority is not found in cacert.pem (certifi==2017.4.17)

Tested with:
`
openssl s_client -connect www.cdta.org:443 -debug -tls1_2 -cipher ECDHE-RSA-AES128-GCM-SHA256

...
depth=0 C = US, ST = New York, L = Albany, O = Capital District Transportation Authority, CN = www.cdta.org
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = New York, L = Albany, O = Capital District Transportation Authority, CN = www.cdta.org
verify error:num=21:unable to verify the first certificate
verify return:1

...

Verify return code: 21 (unable to verify the first certificate)
`

The same certificate details can be found in Firefox 54.0 (32-bit):
![6-29-2017 1-01-39 pm](https://user-images.githubusercontent.com/8913410/27682450-3d7bf9dc-5ccb-11e7-8ac2-48ba8687aa67.png)
A certificate authority can be found on that page under "Entrust Root Certificate Authority—G2" section:
https://www.entrust.com/get-support/ssl-certificate-support/root-certificate-downloads/
Link to file:
https://www.entrust.com/root-certificates/entrust_l1k.cer
`
openssl s_client -connect www.cdta.org:443 -debug -tls1_2 -cipher ECDHE-RSA-AES128-GCM-SHA256 
-CAfile entrust_l1k.cer

...

Verify return code: 0 (ok)
`

Can you please make an update?

**Comment by Lukasa** [comment]
We're not missing the root: the server isn't sending its intermediates. You can see this by looking at the [SSLLabs result for this server](https://www.ssllabs.com/ssltest/analyze.html?d=www.cdta.org&latest) where it shows "Incomplete chain". Certifi does not ship intermediate certificates (there are just far too many of them), so we cannot resolve this problem for you. I recommend contacting the operator of the server, or making a custom trust bundle that *does* include this cert.
