### ISSUE TITLE
Using certifi in PIP environment

### ISSUE THREAD

**Issue by pembo13** [certifi/python-certifi#69]
I seem to always run into certificate issues when I `certifi` is installed. The correct certificate file for my OS is `/etc/pki/tls/certs/ca-bundle.crt` but `certifi.where()` is always set to the bundled .pem file.

What's the correct way to use Certifi so I'm not so regularly hitting SSL verification errors?

**Comment by alex** [comment]
`certifi` provides its own certificate bundle, it does not use the system trust store.

If you want `pip` to use your system's trust store when it verifies certificates you can pass the `--cert` option.

**Comment by pembo13** [comment]
Here's a typical error:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage101.dfw1.clouddrive.com', port=443):
	Max retries exceeded with url: /v1/MossoCloudFS_00000000-0000-4043-0000-bcacf3df1be2/calls (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))
```

I've start passing in the path to the system file whenever I use `requests`, but that's not really an option if I've using requests indirectly. A lot of times, if I uninstall `certifi` the verification failures stop, but a lot of packages require `certifi`.

**Comment by pembo13** [comment]
@alex how do I get other packages to use the system certificate bundle? For more months now I've run into situations where the bundled certificates trigger SSL verification errors. This last time, I had to copy over the bundled one with the system one to get things to work.

**Comment by alex** [comment]
This is really a requests question, but you can set the `SSL_CERT_FILE` environment variable to control the trust store process-wide.

**Comment by pembo13** [comment]
@alex thanks, I'll move this question to `requests` I'll try `SSL_CERT_FILE`, but I haven't really seen it documented anywhere.
