### ISSUE TITLE
local corp certs

### ISSUE THREAD

**Issue by erikbsap** [certifi/python-certifi#71]
Hi is there a way to add my locally installed corporate certificates to certifi somehow?

and why doesn't it by default check for certain locations like [Go seems to do it](https://golang.org/src/crypto/x509/root_linux.go)?

Basically what happens without really having a default solution is [people just ignoring security altogether](https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests).

**Comment by alex** [comment]
certifi's goal is specifically to provide the mozilla trust store, not to manage all trust.

users who want to use locally installed certificates should use their local trust store, instead of certifi.

**Comment by andrewleech** [comment]
@erikbsap I wrote a module to meet the same need (on windows at least). It's a bit nasty under the covers but generally works well: https://pypi.python.org/pypi/python-certifi-win32

Irrespective of this, the default behavior has nothing to do with certifi, typically it's requests - even in the link you posted. Python itself will use the windows system certs, it's requests that so far has decided not to. Ref:
https://bugs.python.org/issue28547#msg279603
https://github.com/requests/requests/issues/2966
