### ISSUE TITLE
version missmatch

### ISSUE THREAD

**Issue by gaborbernat** [certifi/python-certifi#80]
Any reason why on PyPi we have ``2018.1.18`` but the package version says ``2018.01.18``? This makes it hard to write tests that after install what we installed is actually what we have.

**Comment by Lukasa** [comment]
Because PyPI applies a normalisation algorithm to the version number. Not much I can do about that I’m afraid. Easiest thing to do is to treat each component as an integer.

**Comment by gaborbernat** [comment]
I see, given that why not apply the normalization for generating the version number too for the package?

**Comment by Lukasa** [comment]
Basically for internal self-consistency. If we change the scheme we lose consistency with how we previously did this, potentially breaking user code.

**Comment by bhargavrpatel** [comment]
Was just about to open a ticket regarding this. Its a good TIL for myself. Thanks @Lukasa and @gaborbernat.

**Comment by gaborbernat** [comment]
It's a won't fix then I assume :+1:
