### ISSUE TITLE
Installing two packages via conda that require certifi --> IsADirectoryError

### ISSUE THREAD

**Issue by MattKleinsmith** [certifi/python-certifi#81]
**Environment:**

Docker, Ubuntu 16.04, conda, anaconda

Here's the [Dockerfile](https://github.com/MattKleinsmith/dockerfiles/blob/master/errors/certifi/Dockerfile).

**The error:**

`IsADirectoryError(21, 'Is a directory')`

**The following causes the error:**

```
RUN conda install -y -c anaconda certifi
RUN conda install -y mkl-service
```

**Here's a workaround (try to install the package again after the error):**

```
RUN conda install -y -c anaconda certifi
RUN conda install -y mkl-service; exit 0
RUN conda install -y mkl-service
```

**Another sequence that causes the error:**

```
RUN conda install -y mkl-service
RUN conda install -y notebook
RUN conda install -y jupyter_contrib_nbextensions -c conda-forge
```

**Comment by Lukasa** [comment]
We don’t package for Conda ourselves: please take this up with them.
