### ISSUE TITLE
Use Linux distro CA certs when available

### ISSUE THREAD

**Issue by dbnicholson** [certifi/python-certifi#89]
Most Linux distros already provide a trusted set of CA certificates with tools to adjust the certificates as needed. It would be really nice if certifi (i.e. requests) used these rather than the shipped CA bundle. As it turns out, at least Fedora, Debian and SUSE patch their certifi to use the system CA bundle:

https://src.fedoraproject.org/rpms/python-certifi/blob/master/f/certifi-2016.9.26-remove-bundle-cert.patch
https://salsa.debian.org/debian/python-certifi/blob/debian/master/debian/patches/0001-Use-Debian-provided-etc-ssl-certs-ca-certificates.cr.patch
https://build.opensuse.org/package/view_file/devel:languages:python/python-certifi/python-certifi-shipped-requests-cabundle.patch?expand=1

That's all well and good until pip pulls in a new version of certifi and now you're back to the bundled CA certificates.

Would you accept a patch that tries the above paths on Linux before falling back to the bundled CA certs?

**Comment by alex** [comment]
The purpose of certifi is to redistribute the Mozilla trust store; that is the entirety of it's scope.

If you want to make use of your system trust store, I recommend filing a bug with whatever is using certifi.
